import getTr from './fetch.js'
var rulesData = {
  total: 296,
  p: 3,
  ps: 100,
  rules: [
    {
      key: 'eslint:one-var',
      name:
        'enforce variables to be declared either together or separately in functions',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:eslint-issue',
      name: 'EsLint issues that are not yet known to the plugin',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: [],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-component-limit',
      name: 'limit the number of angular components per file (y001)',
      severity: 'CRITICAL',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'best', 'eslint', 'practices'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'BUG',
    },
    {
      key: 'eslint:angular-on-watch',
      name:
        'require $on and $watch deregistration callbacks to be saved in a variable',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'best', 'eslint', 'practices'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'BUG',
    },
    {
      key: 'eslint:angular-di',
      name: 'require a consistent DI syntax',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'convention', 'eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-module-dependency-order',
      name: 'require a consistent order of module dependencies',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'convention', 'eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:newline-per-chained-call',
      name: 'require a newline after each call in a method chain',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-one-dependency-per-line',
      name: 'require all DI parameters to be located in their own line',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'convention', 'eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:newline-before-return',
      name: 'require an empty line before return statements',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-controller-as-vm',
      name:
        'require and specify a capture variable for this in controllers (y032)',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'best', 'eslint', 'practices'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'BUG',
    },
    {
      key: 'eslint:angular-file-name',
      name:
        'require and specify a consistent component name pattern (y120, y121)',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'naming'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-function-type',
      name:
        "require and specify a consistent function style for components ('named' or 'anonymous') (y024)",
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'convention', 'eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-component-name',
      name: 'require and specify a prefix for all component names',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'naming'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-constant-name',
      name: 'require and specify a prefix for all constant names (y125)',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'naming'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-controller-name',
      name:
        'require and specify a prefix for all controller names (y123, y124)',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'naming'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-directive-name',
      name: 'require and specify a prefix for all directive names (y073, y126)',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'naming'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-factory-name',
      name: 'require and specify a prefix for all factory names (y125)',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'naming'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-filter-name',
      name: 'require and specify a prefix for all filter names',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'naming'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-module-name',
      name: 'require and specify a prefix for all module names (y127)',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'naming'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-provider-name',
      name: 'require and specify a prefix for all provider names (y125)',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'naming'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-service-name',
      name: 'require and specify a prefix for all service names (y125)',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'naming'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-value-name',
      name: 'require and specify a prefix for all value names (y125)',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'naming'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-watchers-execution',
      name:
        'require and specify consistent use $scope.digest() or $scope.apply()',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'convention', 'eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:prefer-arrow-callback',
      name: 'require arrow functions as callbacks',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:arrow-body-style',
      name: 'require braces around arrow function bodies',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:use-isnan',
      name: 'require calls to isNaN() when checking for NaN',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'BUG',
    },
    {
      key: 'eslint:prefer-const',
      name:
        'require const declarations for variables that are never reassigned after declared',
      severity: 'CRITICAL',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:new-cap',
      name: 'require constructor names to begin with a capital letter',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:default-case',
      name: 'require default cases in switch statements',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:prefer-destructuring',
      name: 'require destructuring from arrays and/or objects',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-di-order',
      name: 'require DI parameters to be sorted alphabetically',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'convention', 'eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:lines-around-comment',
      name: 'require empty lines around comments',
      severity: 'INFO',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:handle-callback-err',
      name: 'require error handling in callbacks',
      severity: 'CRITICAL',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:guard-for-in',
      name: 'require for-in loops to include an if statement',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:func-name-matching',
      name:
        'require function names to match the name of the variable or property to which they are assigned',
      severity: 'INFO',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:require-yield',
      name: 'require generator functions to contain yield',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:id-match',
      name: 'require identifiers to match a specified regular expression',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:require-jsdoc',
      name: 'require JSDoc comments',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:no-var',
      name: 'require let or const instead of var',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:sort-keys',
      name: 'require object keys to be sorted',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:yoda',
      name: 'require or disallow  Yoda  conditions',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:newline-after-var',
      name: 'require or disallow an empty line after variable declarations',
      severity: 'INFO',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:operator-assignment',
      name: 'require or disallow assignment operator shorthand where possible',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:init-declarations',
      name: 'require or disallow initialization in variable declarations',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:object-shorthand',
      name:
        'require or disallow method and property shorthand syntax for object literals',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:func-names',
      name: 'require or disallow named function expressions',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:eol-last',
      name: 'require or disallow newline at the end of files',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:lines-around-directive',
      name: 'require or disallow newlines around directives',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:one-var-declaration-per-line',
      name: 'require or disallow newlines around variable declarations',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:padded-blocks',
      name: 'require or disallow padding within blocks',
      severity: 'INFO',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:semi',
      name: 'require or disallow semicolons instead of ASI',
      severity: 'INFO',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:template-curly-spacing',
      name:
        'require or disallow spacing around embedded expressions of template strings',
      severity: 'INFO',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:yield-star-spacing',
      name: 'require or disallow spacing around the * in yield* expressions',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:func-call-spacing',
      name:
        'require or disallow spacing between function identifiers and their invocations',
      severity: 'INFO',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:strict',
      name: 'require or disallow strict mode directives',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:comma-dangle',
      name: 'require or disallow trailing commas',
      severity: 'INFO',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:unicode-bom',
      name: 'require or disallow Unicode byte order mark (BOM)',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:arrow-parens',
      name: 'require parentheses around arrow function arguments',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:wrap-iife',
      name: 'require parentheses around immediate function invocations',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:new-parens',
      name: 'require parentheses when invoking a constructor with no arguments',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:wrap-regex',
      name: 'require parenthesis around regex literals',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:quote-props',
      name: 'require quotes around object literal property names',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:global-require',
      name: 'require require() calls to be placed at top-level module scope',
      severity: 'CRITICAL',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:prefer-rest-params',
      name: 'require rest parameters instead of arguments',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:callback-return',
      name: 'require return statements after callbacks',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:consistent-return',
      name:
        'require return statements to either always or never specify values',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:space-infix-ops',
      name: 'require spacing around infix operators',
      severity: 'INFO',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:prefer-spread',
      name: 'require spread operators instead of .apply()',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:constructor-super',
      name: 'require super() calls in constructors',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:symbol-description',
      name: 'require symbol descriptions',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:prefer-template',
      name: 'require template literals instead of string concatenation',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:eqeqeq',
      name: 'require the use of === and !==',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-controller-as-route',
      name: 'require the use of controllerAs in routes or states (y031)',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'best', 'eslint', 'practices'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'BUG',
    },
    {
      key: 'eslint:angular-no-angular-mock',
      name: 'require to use angular.mock methods directly',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:prefer-promise-reject-errors',
      name: 'require using Error objects as Promise rejection reasons',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:vars-on-top',
      name:
        'require var declarations be placed at the top of their containing scope',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:sort-vars',
      name: 'require variables within the same declaration block to be sorted',
      severity: 'MINOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-dumb-inject',
      name:
        'unittest inject functions should only consist of assignments from injected values to describe block variables',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'convention', 'eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-no-cookiestore',
      name: 'use $cookies instead of $cookieStore',
      severity: 'CRITICAL',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'deprecation', 'eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-document-service',
      name: 'use $document instead of document (y180)',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-interval-service',
      name: 'use $interval instead of setInterval (y181)',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-deferred',
      name: 'use $q(function(resolve, reject){}) instead of $q.deferred',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'best', 'eslint', 'practices'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'BUG',
    },
    {
      key: 'eslint:angular-timeout-service',
      name: 'use $timeout instead of setTimeout (y181)',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-window-service',
      name: 'use $window instead of window (y180)',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-angularelement',
      name: 'use angular.element instead of $ or jQuery',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-foreach',
      name: 'use angular.forEach instead of native Array.prototype.forEach',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-typecheck-array',
      name: 'use angular.isArray instead of typeof comparisons',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-typecheck-date',
      name: 'use angular.isDate instead of typeof comparisons',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-definedundefined',
      name:
        'use angular.isDefined and angular.isUndefined instead of other undefined checks',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-typecheck-function',
      name: 'use angular.isFunction instead of typeof comparisons',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-typecheck-number',
      name: 'use angular.isNumber instead of typeof comparisons',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-typecheck-object',
      name: 'use angular.isObject instead of typeof comparisons',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-typecheck-string',
      name: 'use angular.isString instead of typeof comparisons',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-no-service-method',
      name: 'use factory() instead of service() (y040)',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'convention', 'eslint'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-log',
      name: 'use the $log service instead of the console methods',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'eslint', 'wrapper'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'CODE_SMELL',
    },
    {
      key: 'eslint:angular-prefer-component',
      name: 'Use the new api to build components',
      severity: 'MAJOR',
      status: 'READY',
      isTemplate: false,
      tags: [],
      sysTags: ['angular', 'best', 'eslint', 'practices'],
      lang: 'js',
      langName: 'JavaScript',
      params: [],
      type: 'BUG',
    },
  ],
  actives: {
    'eslint:one-var': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:eslint-issue': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-component-limit': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'CRITICAL',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-on-watch': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-di': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-module-dependency-order': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:newline-per-chained-call': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-one-dependency-per-line': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:newline-before-return': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-controller-as-vm': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-file-name': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-function-type': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-component-name': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-constant-name': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-controller-name': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-directive-name': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-factory-name': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-filter-name': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-module-name': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-provider-name': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-service-name': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-value-name': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-watchers-execution': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:prefer-arrow-callback': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:arrow-body-style': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:use-isnan': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:prefer-const': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'CRITICAL',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:new-cap': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:default-case': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:prefer-destructuring': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-di-order': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:lines-around-comment': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'INFO',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:handle-callback-err': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'CRITICAL',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:guard-for-in': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:func-name-matching': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'INFO',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:require-yield': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:id-match': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:require-jsdoc': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:no-var': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:sort-keys': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:yoda': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:newline-after-var': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'INFO',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:operator-assignment': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:init-declarations': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:object-shorthand': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:func-names': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:eol-last': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:lines-around-directive': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:one-var-declaration-per-line': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:padded-blocks': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'INFO',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:semi': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'INFO',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:template-curly-spacing': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'INFO',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:yield-star-spacing': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:func-call-spacing': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'INFO',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:strict': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:comma-dangle': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'INFO',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:unicode-bom': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:arrow-parens': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:wrap-iife': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:new-parens': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:wrap-regex': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:quote-props': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:global-require': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'CRITICAL',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:prefer-rest-params': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:callback-return': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:consistent-return': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:space-infix-ops': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'INFO',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:prefer-spread': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:constructor-super': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:symbol-description': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:prefer-template': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:eqeqeq': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-controller-as-route': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-no-angular-mock': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:prefer-promise-reject-errors': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:vars-on-top': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:sort-vars': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MINOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-dumb-inject': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-no-cookiestore': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'CRITICAL',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-document-service': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-interval-service': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-deferred': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-timeout-service': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-window-service': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-angularelement': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-foreach': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-typecheck-array': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-typecheck-date': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-definedundefined': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-typecheck-function': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-typecheck-number': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-typecheck-object': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-typecheck-string': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-no-service-method': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-log': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
    'eslint:angular-prefer-component': [
      {
        qProfile: 'AXFUqqto0RjRZ6vjq51Y',
        inherit: 'NONE',
        severity: 'MAJOR',
        params: [],
        createdAt: '2020-04-07T20:43:23+0800',
      },
    ],
  },
  qProfiles: {
    AXFUqqto0RjRZ6vjq51Y: {
      name: 'EsLint',
      lang: 'js',
      langName: 'JavaScript',
    },
  },
};
var maps = {
  MINOR:"次要",
  MAJOR:"主要",
  CRITICAL:"严重",
  BLOCKER:"阻断",
  INFO:"提示",
}
        // {
        //     "key": "eslint:no-plusplus",
        //     "name": "disallow the unary operators ++ and --",
        //     "severity": "MINOR",
        //     "status": "READY",
        //     "isTemplate": false,
        //     "tags": [],
        //     "sysTags": [
        //         "eslint"
        //     ],
        //     "lang": "js",
        //     "langName": "JavaScript",
        //     "params": [],
        //     "type": "CODE_SMELL"
        // },
var str = `规则|解释|严重级别| 启用状态\n----|----|-----|-----------\n`
var newData = rulesData.rules.map(function (el, index) {
  getTr(el.name, function (words) {
    debugger
    str = str + `${el.name}|${words}|${maps[el.severity]}|${el.isTemplate}\n`;
  })
});
console.log(str);